-- ============================================================
-- VERIFICATION: Recency rebuild v3 — distinct customer count
-- WHAT: Confirms the distinct customer count after the third
--       amendment (query 74), and checks whether it changed
--       from the second-amendment figure of 5,875.
-- WHY: Same verify-before-trusting discipline applied at every
--      prior amendment. Since customer 16446 still exists in
--      the table (they had other legitimate transactions
--      beyond the excluded 23843 rows), the count should stay
--      at 5,875 — this confirms no customer was fully removed
--      by the third amendment the way 66 were by the second.
-- ============================================================
SELECT COUNT(DISTINCT customer_id) FROM uk_retail.clean_transactions WHERE customer_id IS NOT NULL;